---
- name: (Debian) install deps
  when: ansible_os_family == 'Debian'
  package: name={{item}} state=present
  with_items:
    - libpcre3
    - libpcre3-dev
    - g++

- name: (RedHat) install deps
  when: ansible_os_family == 'RedHat'
  package: name={{item}} state=present
  with_items:
    - pcre
    - pcre-devel
    - gcc-c++
    
- name: download tgz...
  get_url: >-
    url={{swig_tgz_url}}
    dest=/tmp/{{swig_tgz}}
    owner=root
    group=root
    mode=0644
    
- name: unarchive src...
  command: >-
    tar zxvf /tmp/{{swig_tgz}} -C /opt
  args:
    creates: '{{swig_dir}}'

- name: building...
  with_items:
    - ./configure
    - make
    - make install
  command: '{{item}}'
  args:
    chdir: '{{swig_dir}}'

    
