---
- name: (Debian) install deps
  when: ansible_os_family == 'Debian'
  apt: name={{item}} state=latest
  with_items:
    - libpcre3
    - libpcre3-dev

- name: (RedHat) install desp
  when: ansible_os_family == 'RedHat'
  yum: name={{item}} state=latest
  with_items:
    - pcre
    - pcre-devel
    
- name: download tgz...
  get_url: >-
    url={{swig_tgz_url}}
    dest=/tmp/{{swig_tgz}}
    owner=root
    group=root
    mode=0644
    
- name: install src...
  unarchive: >-
    copy=no
    src=/tmp/{{swig_tgz}}
    dest=/opt
    owner=root
    group=root
    mode=0755

- name: building...
  with_items:
    - ./configure
    - make
    - make install
  command: '{{item}}'
  args:
    chdir: '{{swig_dir}}'

    