---
- name: resolve platform specific vars
  include_vars: "{{item}}"
  with_first_found:
    - "{{ansible_distribution}}-{{ansible_distribution_release}}.yml"
    - "{{ansible_distribution}}.yml"
    - "{{ansible_os_family}}.yml"

- name: install pkg deps
  become: yes
  become_user: root
  package: name={{item}} state=present
  with_items: '{{swig_dep_pkgs}}'

- name: download tgz...
  become: yes
  become_user: root
  get_url: >-
    url={{swig_tgz_url}}
    dest=/tmp/{{swig_tgz}}
    mode=0644
    timeout=300
    
- name: unarchive src...
  become: yes
  become_user: root
  unarchive: >-
    copy=no
    src=/tmp/{{swig_tgz}}
    dest=/opt
    creates={{swig_dir}}

- name: building...
  become: yes
  become_user: root
  with_items:
    - ./configure
    - make
    - make install
  command: '{{item}}'
  args:
    chdir: '{{swig_dir}}'

    
