---
- include_role:
    name: andrewrothstein.unarchive-deps
- include_role:
    name: andrewrothstein.gcc-toolbox
- name: installing OS pkg deps
  become: '{{ swig_privilege_escalate }}'
  become_user: root
  package:
    name: '{{ swig_dep_pkgs }}'
    state: present

- name: downloading {{ swig_tgz_url }}
  become: '{{ swig_privilege_escalate }}'
  become_user: root
  get_url:
    url: '{{ swig_tgz_url }}'
    dest: '{{ swig_tmp_tgz }}'
    mode: '0644'
    checksum: '{{ swig_checksum }}'
    timeout: '{{ swig_download_timeout_seconds }}'

- name: unarchiving {{ swig_tmp_tgz }} to {{ swig_build_parent_dir }}
  become: '{{ swig_privilege_escalate }}'
  become_user: root
  unarchive:
    remote_src: true
    src: '{{ swig_tmp_tgz }}'
    dest: '{{ swig_build_parent_dir }}'
    creates: '{{ swig_dir }}'

- name: configuring in {{ swig_dir }}
  become: '{{ swig_privilege_escalate }}'
  become_user: root
  command: '{{ swig_dir }}/configure'
  args:
    chdir: '{{ swig_dir }}'
    creates: '{{ swig_dir }}/CCache/Makefile'

- name: building with make in {{ swig_dir }}
  become: '{{ swig_privilege_escalate }}'
  become_user: root
  command: make
  args:
    chdir: '{{ swig_dir }}'
    creates: '{{ swig_dir }}/swig'

- name: installing with make in {{ swig_dir }}
  become: '{{ swig_privilege_escalate }}'
  become_user: root
  command: make install
  args:
    chdir: '{{ swig_dir }}'
    creates: /usr/local/bin/swig
