---
- name: install pkg deps
  become: '{{ swig_privilege_escalate }}'
  become_user: root
  package:
    name: '{{ swig_dep_pkgs }}'
    state: present

- name: download tgz...
  become: '{{ swig_privilege_escalate }}'
  become_user: root
  get_url:
    url: '{{ swig_tgz_url }}'
    dest: /tmp/{{ swig_tgz }}
    mode: '0644'
    checksum: '{{ swig_checksum }}'
    timeout: '{{ swig_download_timeout_seconds }}'
    
- name: unarchive src...
  become: '{{ swig_privilege_escalate }}'
  become_user: root
  unarchive:
    remote_src: yes
    src: /tmp/{{ swig_tgz }}
    dest: '{{ swig_build_parent_dir }}'
    creates: '{{ swig_dir }}'

- name: configuring...
  become: '{{ swig_privilege_escalate }}'
  become_user: root
  command: ./configure
  args:
    chdir: '{{ swig_dir }}'
    creates: '{{ swig_dir }}/CCache/Makefile'

- name: building...
  become: '{{ swig_privilege_escalate }}'
  become_user: root
  command: make
  args:
    chdir: '{{ swig_dir }}'
    creates: '{{ swig_dir }}/swig'

- name: building...
  become: '{{ swig_privilege_escalate }}'
  become_user: root
  command: make install
  args:
    chdir: '{{ swig_dir }}'
    creates: /usr/local/bin/swig
