---
- name: Installing andrewrothstein.unarchivedeps
  ansible.builtin.include_role:
    name: andrewrothstein.unarchivedeps
- name: Installing andrewrothstein.gcc_toolbox
  ansible.builtin.include_role:
    name: andrewrothstein.gcc_toolbox
- name: Installing OS pkg deps
  become: '{{ swig_privilege_escalate }}'
  become_user: root
  ansible.builtin.package:
    name: '{{ swig_dep_pkgs }}'
    state: present

- name: Downloading {{ swig_tgz_url }}
  become: '{{ swig_privilege_escalate }}'
  become_user: root
  ansible.builtin.get_url:
    url: '{{ swig_tgz_url }}'
    dest: '{{ swig_tmp_tgz }}'
    mode: '644'
    checksum: '{{ swig_checksum }}'
    timeout: '{{ swig_download_timeout_seconds }}'

- name: Unarchiving {{ swig_tmp_tgz }} to {{ swig_build_parent_dir }}
  become: '{{ swig_privilege_escalate }}'
  become_user: root
  ansible.builtin.unarchive:
    remote_src: true
    src: '{{ swig_tmp_tgz }}'
    dest: '{{ swig_build_parent_dir }}'
    creates: '{{ swig_dir }}'

- name: Configuring in {{ swig_dir }}
  become: '{{ swig_privilege_escalate }}'
  become_user: root
  ansible.builtin.command: '{{ swig_dir }}/configure'
  args:
    chdir: '{{ swig_dir }}'
    creates: '{{ swig_dir }}/CCache/Makefile'

- name: Building with make in {{ swig_dir }}
  become: '{{ swig_privilege_escalate }}'
  become_user: root
  ansible.builtin.command: make
  args:
    chdir: '{{ swig_dir }}'
    creates: '{{ swig_dir }}/swig'

- name: Installing with make in {{ swig_dir }}
  become: '{{ swig_privilege_escalate }}'
  become_user: root
  ansible.builtin.command: make install
  args:
    chdir: '{{ swig_dir }}'
    creates: /usr/local/bin/swig
